"""
TravelPlannerPro - PDF Generator
Creates professional travel reports using ReportLab.
"""

import io
import os
import logging
from datetime import datetime
from typing import Dict, Any

logger = logging.getLogger(__name__)

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm, mm
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, PageBreak, KeepTogether,
    )
    from reportlab.platypus.flowables import HRFlowable
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False
    logger.warning("ReportLab not installed. PDF export unavailable.")


# ─── Brand Colors (only defined when ReportLab is available) ──────────────────
if REPORTLAB_AVAILABLE:
    PRIMARY    = colors.HexColor("#1a1a2e")
    ACCENT     = colors.HexColor("#0f3460")
    GOLD       = colors.HexColor("#e94560")
    LIGHT_BLUE = colors.HexColor("#16213e")
    TEXT_DARK  = colors.HexColor("#1f2328")
    TEXT_MUTED = colors.HexColor("#57606a")
    BG_LIGHT   = colors.HexColor("#f7f8fa")
    WHITE      = colors.white
    BLACK      = colors.black


def generate_travel_pdf(
    travel_data: Dict[str, Any],
    itinerary_text: str,
    output_path: str,
) -> bool:
    """
    Generate a professional travel report PDF.

    Args:
        travel_data: Dict with trip details (source, destination, dates, etc.)
        itinerary_text: Raw itinerary markdown/text from IBM Granite.
        output_path: Full path where the PDF will be saved.

    Returns:
        True on success, False on failure.
    """
    if not REPORTLAB_AVAILABLE:
        logger.error("ReportLab not available for PDF generation.")
        return False

    try:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        doc = SimpleDocTemplate(
            output_path,
            pagesize=A4,
            rightMargin=2 * cm,
            leftMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
            title="Travel Itinerary — TravelPlannerPro",
            author="TravelPlannerPro | IBM Granite",
        )

        styles = _build_styles()
        story = []

        # Cover Page
        _add_cover_page(story, styles, travel_data)
        story.append(PageBreak())

        # Trip Summary Table
        _add_trip_summary(story, styles, travel_data)
        story.append(Spacer(1, 0.5 * cm))

        # Main Itinerary Content
        _add_itinerary_content(story, styles, itinerary_text)

        # Footer Note
        story.append(Spacer(1, 1 * cm))
        story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
        story.append(Spacer(1, 0.3 * cm))
        story.append(Paragraph(
            "Generated by <b>TravelPlannerPro</b> · Powered by <b>IBM Granite</b> via IBM watsonx.ai<br/>"
            "IBM SkillsBuild Final Project | Edunet Foundation | Problem Statement No. 5",
            styles["footer_note"],
        ))

        doc.build(story)
        logger.info(f"PDF generated: {output_path}")
        return True

    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        return False


def _build_styles() -> Dict[str, ParagraphStyle]:
    """Build custom paragraph styles for the PDF."""
    base = getSampleStyleSheet()

    styles = {
        "cover_title": ParagraphStyle(
            "CoverTitle",
            parent=base["Title"],
            fontSize=32,
            textColor=WHITE,
            alignment=TA_CENTER,
            spaceAfter=8,
            fontName="Helvetica-Bold",
        ),
        "cover_subtitle": ParagraphStyle(
            "CoverSubtitle",
            parent=base["Normal"],
            fontSize=14,
            textColor=colors.HexColor("#e0e0e0"),
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "cover_route": ParagraphStyle(
            "CoverRoute",
            parent=base["Normal"],
            fontSize=22,
            textColor=GOLD,
            alignment=TA_CENTER,
            spaceAfter=6,
            fontName="Helvetica-Bold",
        ),
        "cover_meta": ParagraphStyle(
            "CoverMeta",
            parent=base["Normal"],
            fontSize=11,
            textColor=colors.HexColor("#cccccc"),
            alignment=TA_CENTER,
            spaceAfter=3,
        ),
        "section_heading": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading1"],
            fontSize=15,
            textColor=ACCENT,
            spaceAfter=6,
            spaceBefore=12,
            fontName="Helvetica-Bold",
            borderPad=4,
        ),
        "sub_heading": ParagraphStyle(
            "SubHeading",
            parent=base["Heading2"],
            fontSize=12,
            textColor=LIGHT_BLUE,
            spaceAfter=4,
            spaceBefore=8,
            fontName="Helvetica-Bold",
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontSize=10,
            textColor=TEXT_DARK,
            spaceAfter=4,
            leading=15,
            alignment=TA_JUSTIFY,
        ),
        "bullet": ParagraphStyle(
            "Bullet",
            parent=base["Normal"],
            fontSize=10,
            textColor=TEXT_DARK,
            spaceAfter=2,
            leading=14,
            leftIndent=12,
            bulletIndent=0,
        ),
        "footer_note": ParagraphStyle(
            "FooterNote",
            parent=base["Normal"],
            fontSize=8,
            textColor=TEXT_MUTED,
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "table_header": ParagraphStyle(
            "TableHeader",
            parent=base["Normal"],
            fontSize=10,
            textColor=WHITE,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
        ),
        "table_cell": ParagraphStyle(
            "TableCell",
            parent=base["Normal"],
            fontSize=9,
            textColor=TEXT_DARK,
            alignment=TA_LEFT,
        ),
    }
    return styles


def _add_cover_page(story, styles, travel_data):
    """Add a premium cover page to the PDF."""
    story.append(Spacer(1, 2 * cm))

    story.append(Paragraph("✈  TravelPlannerPro", styles["cover_title"]))
    story.append(Paragraph("AI-Powered Travel Itinerary", styles["cover_subtitle"]))
    story.append(Spacer(1, 0.5 * cm))

    source = travel_data.get("source", "Origin")
    destination = travel_data.get("destination", "Destination")
    story.append(Paragraph(f"{source}  →  {destination}", styles["cover_route"]))
    story.append(Spacer(1, 0.8 * cm))

    # Horizontal rule
    story.append(HRFlowable(width="80%", thickness=2, color=GOLD, hAlign="CENTER"))
    story.append(Spacer(1, 0.8 * cm))

    # Trip metadata
    meta_items = [
        ("📅 Departure", travel_data.get("departure_date", "TBD")),
        ("🏠 Return", travel_data.get("return_date", "TBD")),
        ("👥 Travellers", str(travel_data.get("travelers", 1))),
        ("💰 Budget", str(travel_data.get("budget", "TBD"))),
        ("🏨 Accommodation", travel_data.get("hotel_pref", "TBD")),
        ("🚌 Transport", travel_data.get("transport", "TBD")),
    ]

    for label, value in meta_items:
        story.append(Paragraph(f"<b>{label}:</b>  {value}", styles["cover_meta"]))

    story.append(Spacer(1, 1.5 * cm))
    story.append(HRFlowable(width="60%", thickness=1, color=TEXT_MUTED, hAlign="CENTER"))
    story.append(Spacer(1, 0.5 * cm))

    # IBM Granite badge
    story.append(Paragraph(
        "Powered by <b>IBM Granite</b> | IBM watsonx.ai",
        styles["cover_subtitle"],
    ))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        styles["cover_meta"],
    ))
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(
        "IBM SkillsBuild Final Project · Edunet Foundation",
        styles["cover_meta"],
    ))


def _add_trip_summary(story, styles, travel_data):
    """Add a trip summary table."""
    story.append(Paragraph("📋 Trip Summary", styles["section_heading"]))

    interests = travel_data.get("interests", "Not specified")
    special = travel_data.get("special_requests", "None")

    table_data = [
        [Paragraph("Field", styles["table_header"]), Paragraph("Details", styles["table_header"])],
        ["🛫 From", travel_data.get("source", "—")],
        ["🛬 To", travel_data.get("destination", "—")],
        ["📅 Departure", travel_data.get("departure_date", "—")],
        ["🏠 Return", travel_data.get("return_date", "—")],
        ["👥 Travellers", str(travel_data.get("travelers", 1))],
        ["💰 Budget", travel_data.get("budget", "—")],
        ["🚌 Transport", travel_data.get("transport", "—")],
        ["🏨 Hotel Pref.", travel_data.get("hotel_pref", "—")],
        ["🎯 Interests", interests[:80] + "..." if len(interests) > 80 else interests],
        ["💬 Special Requests", special[:80] + "..." if len(special) > 80 else special],
    ]

    table = Table(table_data, colWidths=[5 * cm, 12 * cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 10),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("BACKGROUND", (0, 1), (-1, -1), BG_LIGHT),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, BG_LIGHT]),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("ROWHEIGHT", (0, 0), (-1, -1), 22),
    ]))
    story.append(table)


def _add_itinerary_content(story, styles, itinerary_text: str):
    """Parse and add the itinerary text to the PDF."""
    story.append(Paragraph("🗺️ Your Complete Travel Itinerary", styles["section_heading"]))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
    story.append(Spacer(1, 0.3 * cm))

    lines = itinerary_text.split("\n")

    for line in lines:
        stripped = line.strip()
        if not stripped:
            story.append(Spacer(1, 0.2 * cm))
            continue

        # Detect markdown headings
        if stripped.startswith("### "):
            text = stripped[4:].replace("**", "").replace("*", "")
            story.append(Paragraph(text, styles["sub_heading"]))

        elif stripped.startswith("## "):
            text = stripped[3:].replace("**", "").replace("*", "")
            story.append(Paragraph(text, styles["section_heading"]))

        elif stripped.startswith("# "):
            text = stripped[2:].replace("**", "").replace("*", "")
            story.append(Paragraph(text, styles["section_heading"]))

        elif stripped.startswith("---"):
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e5e7eb")))
            story.append(Spacer(1, 0.2 * cm))

        elif stripped.startswith("- ") or stripped.startswith("• "):
            text = stripped[2:].replace("**", "<b>").replace("*", "")
            story.append(Paragraph(f"• {text}", styles["bullet"]))

        elif stripped.startswith("**") and stripped.endswith("**"):
            text = stripped[2:-2]
            story.append(Paragraph(f"<b>{text}</b>", styles["sub_heading"]))

        else:
            # Regular body text — handle basic markdown
            text = stripped.replace("**", "<b>", 1)
            if "<b>" in text:
                text = text.replace("**", "</b>", 1)
            text = text.replace("*", "")
            try:
                story.append(Paragraph(text, styles["body"]))
            except Exception:
                story.append(Paragraph(stripped, styles["body"]))
